### ISSUE TITLE
You should update your Donation Address (reuse)

### ISSUE THREAD

**Issue by oyren** [noneymous/iota-consensus-presentation#5]
https://thetangle.org/address/QPLGOG9PMIMUAW9UDMUNZQHPXZPXDNGLBEIHILXHWHIOFHLIHPDDERXAJQKUQDEORMHSUWVZQE9JYSHIW

**Comment by noneymous** [comment]
Thank's, I know. But was too lazy for some unlikely donations. But you are right, I updated the address now. :)
